#!/bin/bash

# Ensure the necessary paths are included in $PATH
export PATH=$PATH:/etc/profiles/per-user/monu/bin:/run/current-system/sw/bin

# Parameters for the repository, password file, and email address
REPO_PATH="$1"
PASSWORD_FILE="$2"
MY_EMAIL_ADDRESS="$3"
TODAY=$(date +%Y-%m-%d)
HOSTNAME=$(hostname)

echo "Hostname: $HOSTNAME, Repository: $REPO_PATH, Date: $TODAY"

# Check if repository, password, and email parameters are provided
if [[ -z "$REPO_PATH" || -z "$PASSWORD_FILE" || -z "$MY_EMAIL_ADDRESS" ]]; then
  echo "Usage: $0 <repository_path> <password_file> <email_address>"
  exit 1
fi

# Handle rclone config if applicable
if [[ "$REPO_PATH" == rclone:* ]]; then
  export RCLONE_CONFIG=/run/agenix/service/rclone/conf
fi

# Unlock the repository if locked
restic -r "$REPO_PATH" --password-file "$PASSWORD_FILE" unlock

# Check if backup was taken today
if ! restic -r "$REPO_PATH" --password-file "$PASSWORD_FILE" snapshots | grep -q "$TODAY"; then
  echo "[WARNING] No backup taken today for $REPO_PATH"
  echo -e "Subject: Restic Backup Alert - $HOSTNAME\n\nNo backup taken today for $REPO_PATH!" | msmtp "$MY_EMAIL_ADDRESS"
fi

# Check the repository integrity
if ! restic -r "$REPO_PATH" --password-file "$PASSWORD_FILE" check --read-data-subset=0.1% --no-lock --no-cache; then
  echo "[ERROR] Repository $REPO_PATH failed the integrity check"
  echo -e "Subject: Restic Repository Health Alert - $HOSTNAME\n\nRepository $REPO_PATH failed the integrity check!" | msmtp "$MY_EMAIL_ADDRESS"
else
  echo "Repository $REPO_PATH passed the integrity check"
fi
