#!/bin/sh
set -euo pipefail

# Create 'nebula' directory structure
mkdir -p /mnt/data
chown monu:monu /mnt/data/

# monu
runuser -u monu -- mkdir -p /home/monu/{.config,.emacs.d,.gnupg,.local/share} /mnt/data/{apps,nebula/{sync,dotfiles,nixos-config}}

# root
mkdir -p /root/{.config,.emacs.d,.gnupg,.local/share}
