#!/bin/sh
set -euo pipefail

current_hostname=$(hostname)

if [ "$current_hostname" = "nova" ]; then
    GIT_PROTOCOL="git@github.com:"
else
    GIT_PROTOCOL="https://github.com/"
fi

update_repo() {
    local repo_dir=$1
    local repo_url=$2
    cd "$repo_dir"

    if [ ! -d "$repo_dir/.git" ]; then
        runuser -u monu -- git clone "$repo_url" "$repo_dir"
    else
        runuser -u monu -- git pull origin main
    fi
}

DOTFILES_DIR="/mnt/data/nebula/dotfiles"
update_repo "$DOTFILES_DIR" "${GIT_PROTOCOL}parveshdhull/dotfiles"

runuser -u monu -- stow --adopt -d "$DOTFILES_DIR" -t /home/monu -S .
stow --adopt -d "$DOTFILES_DIR" -t /root -S .

NIXOS_DIR="/mnt/data/nebula/nixos-config"
update_repo "$NIXOS_DIR" "${GIT_PROTOCOL}parveshdhull/nixos-config"
