#!/bin/bash
set -euo pipefail

# Execute signal-cli receive
signal-cli receive

# Check the list of groups
if [ $(signal-cli listGroups 2>&1 | grep -c 'Alertbot') -ne 1 ]; then
	echo -e "To: $MY_EMAIL_ADDRESS\nSubject: Error\n\nSignal list groups don't have Alertbot" | msmtp -t
fi
